spring:
    datasource:
        url: jdbc:h2:file:./data/brasovbus
        driverClassName: org.h2.Driver
        username: sa
        password:
    liquibase:
        change-log: classpath:db/changelog/db.changelog-master.xml
        enabled: true
